// Code generated by mockery v2.48.0. DO NOT EDIT.

package weather

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetOutdoorDewPoint provides a mock function with given fields: ctx
func (_m *MockClient) GetOutdoorDewPoint(ctx context.Context) (float64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOutdoorDewPoint")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (float64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) float64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetOutdoorDewPoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOutdoorDewPoint'
type MockClient_GetOutdoorDewPoint_Call struct {
	*mock.Call
}

// GetOutdoorDewPoint is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) GetOutdoorDewPoint(ctx interface{}) *MockClient_GetOutdoorDewPoint_Call {
	return &MockClient_GetOutdoorDewPoint_Call{Call: _e.mock.On("GetOutdoorDewPoint", ctx)}
}

func (_c *MockClient_GetOutdoorDewPoint_Call) Run(run func(ctx context.Context)) *MockClient_GetOutdoorDewPoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_GetOutdoorDewPoint_Call) Return(_a0 float64, _a1 error) *MockClient_GetOutdoorDewPoint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetOutdoorDewPoint_Call) RunAndReturn(run func(context.Context) (float64, error)) *MockClient_GetOutdoorDewPoint_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
