name: Go CI

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'go/go-dew/**'
  pull_request:
    paths:
      - 'go/go-dew/**'

jobs:
  lint-test-build:
    name: lint-test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      
      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: ./go/go-dew/cmd/server
      
      - name: Run Go Tests
        run: |
          cd ./go/go-dew
          go test ./...

      - name: Build the Go Project
        run: |
          cd ./go/go-dew/cmd/server
          go build -o go-dew-app
