name: Go Test

on:
  workflow_run:
    workflows: ["Go Lint"]
    types:
      - completed

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if linting was successful
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install Wire
        run: |
          cd ./go/go-dew/cmd/server
          go install github.com/google/wire/cmd/wire@latest
      
      - name: Generate Code with Wire
        run: |
          cd ./go/go-dew/cmd/server
          wire
      
      - name: Run Go Tests
        run: |
          cd ./go/go-dew/
          go test ./...
