name: Rust CI

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'rust/arDEWino-rs/**'
  pull_request:
    paths:
      - 'rust/arDEWino-rs/**'

jobs:
  lint-test-build:
    name: lint-test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      
      - name: Install libudev development package
        run: sudo apt-get install -y libudev-dev

      - name: Run Clippy
        run: |
          cd ./rust/arDEWino-rs
          cargo clippy --all-features -- -D warnings
      - name: Run Tests
        run: |
          cd ./rust/arDEWino-rs
          cargo test --all-features
      - name: Build the Rust Project
        run: |
          cd ./rust/arDEWino-rs
          cargo build --all-features --release
