name: rust lint
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      
      - name: Install libudev development package
        run: sudo apt-get install -y libudev-dev

      - name: Run Clippy
        run: |
            cd rust/arDEWino-rs
            cargo clippy --all-features -- -D warnings
